// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7lp8P4Mdo-ihDobWqPSJxWeKCxTTMVIo',
    appId: '1:790650417677:web:3f6c8879d97e5128045b44',
    messagingSenderId: '790650417677',
    projectId: 'first-app-835e2',
    authDomain: 'first-app-835e2.firebaseapp.com',
    databaseURL: 'https://first-app-835e2-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-835e2.firebasestorage.app',
    measurementId: 'G-XBXYXXQ8KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATTJHpKPE77EaWWKCO_6MZRTU_ekzt7ns',
    appId: '1:790650417677:android:652cf23699a6f203045b44',
    messagingSenderId: '790650417677',
    projectId: 'first-app-835e2',
    databaseURL: 'https://first-app-835e2-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-835e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCZ0yQKFMeNmDbIcWeZ4p3fw1LOVPHbtM',
    appId: '1:790650417677:ios:4178f7deeb4a426e045b44',
    messagingSenderId: '790650417677',
    projectId: 'first-app-835e2',
    databaseURL: 'https://first-app-835e2-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-835e2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCZ0yQKFMeNmDbIcWeZ4p3fw1LOVPHbtM',
    appId: '1:790650417677:ios:4178f7deeb4a426e045b44',
    messagingSenderId: '790650417677',
    projectId: 'first-app-835e2',
    databaseURL: 'https://first-app-835e2-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-835e2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7lp8P4Mdo-ihDobWqPSJxWeKCxTTMVIo',
    appId: '1:790650417677:web:7d1ccbffc82d9f3b045b44',
    messagingSenderId: '790650417677',
    projectId: 'first-app-835e2',
    authDomain: 'first-app-835e2.firebaseapp.com',
    databaseURL: 'https://first-app-835e2-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-835e2.firebasestorage.app',
    measurementId: 'G-HM39BVGYPR',
  );
}
